language: python
python:
  - "2.7"

cache: pip

services:
  - docker

env:
  global:
    - IMG=tdmproject/ckan-core

script:
  - make images

deploy:
  - provider: script
    script: bash .travis/push.sh
    on:
      repo: tdm-project/ckan
      branch: v2.8
